### ISSUE TITLE
Launching a node on Java x32

### ISSUE THREAD

**Issue by LazyPotato** [aimmac23/selenium-video-node#19]
Hi,
 I've got an exception trying to launch a node on Windows 7 x32 machine (running x32 Java, version 1.8.0_20)
```
11:35:12.712 INFO - Could not load 64 bit native libraries - attempting 32 bit instead

Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'vpx': Native library (win32-x86/vpx.dll) not found in resource path 
([file:/C:/Tools/SeleniumGrid/selenium-video-node-1.8.jar, file:/C:/Tools/SeleniumGrid/selenium-server-standalone-2.46.0.jar])
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:271)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:398)
        at com.sun.jna.Library$Handler.<init>(Library.java:147)
        at com.sun.jna.Native.loadLibrary(Native.java:412)
        at com.sun.jna.Native.loadLibrary(Native.java:391)
        at com.aimmac23.node.jna.JnaLibraryLoader.tryLoadLibraries(JnaLibraryLoader.java:125)
        at com.aimmac23.node.jna.JnaLibraryLoader.tryBitDepth(JnaLibraryLoader.java:150)
        at com.aimmac23.node.jna.JnaLibraryLoader.init(JnaLibraryLoader.java:110)
        at com.aimmac23.node.RecordVideoCallable.<clinit>(RecordVideoCallable.java:26)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at com.aimmac23.node.servlet.VideoRecordingControlServlet.<clinit>(VideoRecordingControlServlet.java:40)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.openqa.grid.web.utils.ExtraServletUtil.createServlet(ExtraServletUtil.java:38)
        at org.openqa.grid.internal.utils.SelfRegisteringRemote.startRemoteServer(SelfRegisteringRemote.java:128)
        at org.openqa.grid.selenium.GridLauncher.main(GridLauncher.java:85)
```
It runs successfully with x64 Java on other machine, but i can't use it on x32 machine. Could you suggest any solution, please?

**Comment by aimmac23** [comment]
Hi LazyPotato,

I think the Windows 32bit support is now breaking because Selenium have updated their JNA library version in Selenium 2.46 - however I haven't spotted why its breaking, and only breaking for 32bit Windows.

Double check that the versions of Selenium you are using are the same - as a workaround try to use Selenium 2.45 and see if that helps.

Let me know if that helps - I'll see what I can do this weekend.

**Comment by LazyPotato** [comment]
Hi,
Unfortunately, using Selenium 2.45 doesn't help, it crashes with the same exception.

**Comment by aimmac23** [comment]
Hi LazyPotato,

I've tried to reproduce the problem on my 32-bit Windows VM, but without success. I did use a slightly different Java version (1.8u25), and I had to use Windows Server 2008, so its a slightly different configuration.

Could you try running it again with -Djna.debug_load=true at the start of your Java command line arguements, and pasting the results? For example, I get:

http://pastebin.com/kpEJEKRS

**Comment by helixquar** [comment]
Had the same problem in Windows XP, Modern.IE VM. Ran dependency walker on libvpx.dll. Says it's missing libgcc_s_dw2-1.dll. Solved by pasting a copy of libgcc_s_dw2-1.dll to one of the directories in the PATH environment var.

**Comment by aimmac23** [comment]
Hi helixquar,

It looks like you've found the problem - all the 32 bit Windows binaries seem to be dynamically linked to the GCC compiler's version of libc/libc++ (but not the 64 bit versions). I couldn't find the problem when testing it because the VM I was using had GCC installed...

I'll get the binaries recompiled after Christmas, I think - there seems to be a flag to statically link them against the relevant library instead.

Thanks for the help,

Alasdair Macmillan

**Comment by aimmac23** [comment]
Hi LazyPotato,

I've re-compiled the 32-bit Windows binaries to not have a dynamic dependency on GCC's libc, and tested that the node starts up on a fresh 32-bit Windows VM. Let me know if you have any other issues.

Thanks,

Alasdair
