### ISSUE TITLE
Not Working on Windows Server 2012 R2 64 bit

### ISSUE THREAD

**Issue by sahajamit** [aimmac23/selenium-video-node#33]
When I started the selenium node with this command:

"%JAVA_HOME%\bin\java" -Dwebdriver.chrome.driver=./chromedriver.exe -cp selenium-video-node-1.8.jar;selenium-server-standalone-2.53.1.jar org.openqa.grid.selenium.GridLauncher -servlets com.aimmac23.node.servlet.VideoRecordingControlServlet -proxy com.aimmac23.hub.proxy.VideoProxy -role node  -nodeConfig ./nodeConfig.json 

I got this error:

09:31:10.187 INFO - Launching a Selenium Grid node
09:31:10.538 INFO - Java: Oracle Corporation 24.80-b11
09:31:10.538 INFO - OS: Windows Server 2012 R2 6.3 x86
09:31:10.542 INFO - v2.53.1, with Core v2.53.1. Built from revision a36b8b1
09:31:10.577 INFO - Driver class not found: com.opera.core.systems.OperaDriver
09:31:10.577 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
09:31:10.582 INFO - Driver provider org.openqa.selenium.safari.SafariDriver registration is skipped:
registration capabilities Capabilities [{platform=MAC, browserName=safari, version=}] does not match the current platform WIN8
09:31:10.582 INFO - Driver class not found: org.openqa.selenium.htmlunit.HtmlUnitDriver
09:31:10.583 INFO - Driver provider org.openqa.selenium.htmlunit.HtmlUnitDriver is not registered
09:31:10.945 INFO - Could not load 64 bit native libraries - attempting 32 bit instead
Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'vpx': Native library (win32-x86/vpx.dll) not found in resource path
 ([file:/D:/Selenium/selenium-video-node-1.8.jar, file:/D:/Selenium/selenium-server-standalone-2.53.1.jar])
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:271)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:398)
        at com.sun.jna.Library$Handler.<init>(Library.java:147)
        at com.sun.jna.Native.loadLibrary(Native.java:412)
        at com.sun.jna.Native.loadLibrary(Native.java:391)
        at com.aimmac23.node.jna.JnaLibraryLoader.tryLoadLibraries(JnaLibraryLoader.java:125)
        at com.aimmac23.node.jna.JnaLibraryLoader.tryBitDepth(JnaLibraryLoader.java:150)
        at com.aimmac23.node.jna.JnaLibraryLoader.init(JnaLibraryLoader.java:110)
        at com.aimmac23.node.RecordVideoCallable.<clinit>(RecordVideoCallable.java:26)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:195)
        at com.aimmac23.node.servlet.VideoRecordingControlServlet.<clinit>(VideoRecordingControlServlet.java:40)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:195)
        at org.openqa.selenium.server.SeleniumServer.createServlet(SeleniumServer.java:636)
        at org.openqa.selenium.server.SeleniumServer.registerExtraServlets(SeleniumServer.java:621)
        at org.openqa.selenium.server.SeleniumServer.<init>(SeleniumServer.java:256)
        at org.openqa.grid.selenium.GridLauncher$3.launch(GridLauncher.java:91)
        at org.openqa.grid.selenium.GridLauncher.main(GridLauncher.java:127)

**Comment by aimmac23** [comment]
Hi sahajamit,

I think it may be the same problem as issue #19 - I suggest trying the latest version from the Maven repositories (version 2.2):

http://repo1.maven.org/maven2/com/aimmac23/selenium-video-node/

Thanks,

Alasdair

**Comment by sahajamit** [comment]
Thanks a lot Alasdair for your prompt reply. I resolved this error after upgrading to version 2.2.

Now I am facing another issue. As my node machine is a remote VM (Windows Server 2012 R2) and when I closed my RDP session to this box then all the videos getting recorded are coming complete black.

Is it necessary to have active RDP sessions to get this recording done?

**Comment by aimmac23** [comment]
Hi sahajamit,

Indeed - you have to have either an active RDP session, or have a real local login in your VM. This is because Windows doesn't render anything when the RDP client has been disconnected.

You should be able to set this up by installing some VNC software, and getting a user to auto-login at startup. This should allow you to launch a selenium node without using RDP.

I think since this keeps coming up we should have a proper set of detailed instructions for this.

Thanks,

Alasdair

**Comment by sahajamit** [comment]
Thanks Alasdair. I will try to solve this problem by installing VNC server on these machines.

**Comment by aimmac23** [comment]
I assume sahajamit has got it working, so closing issue/

**Comment by hemanthsridhar** [comment]
@aimmac23 : will this issue exist if it is a MAC OSX VM?
