### ISSUE TITLE
ERROR - Couldn't correct Selenium registration request

### ISSUE THREAD

**Issue by madaniel** [aimmac23/selenium-video-node#35]
this code may need recompiling to support new code changes. Please file a bug against the selenium-video-node project, and attach this stacktrace.

java.lang.IllegalAccessException: Class com.aimmac23.hub.proxy.RegistrationRequestCorrector$V3ConfigurationCorrector can not access a member of class org.openqa.grid.internal.utils.configuration.GridConfiguration with modifiers "public"
	at sun.reflect.Reflection.ensureMemberAccess(Unknown Source)
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(Unknown Source)
	at java.lang.reflect.AccessibleObject.checkAccess(Unknown Source)
	at java.lang.reflect.Field.get(Unknown Source)
	at com.aimmac23.hub.proxy.RegistrationRequestCorrector$V3ConfigurationCorrector.fixupConfig(RegistrationRequestCorrector.java:64)
	at com.aimmac23.hub.proxy.RegistrationRequestCorrector.correctRegistrationRequest(RegistrationRequestCorrector.java:33)
	at com.aimmac23.hub.proxy.VideoProxy.<init>(VideoProxy.java:36)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.grid.internal.BaseRemoteProxy.getNewInstance(BaseRemoteProxy.java:369)
	at org.openqa.grid.web.servlet.RegistrationServlet.process(RegistrationServlet.java:104)
	at org.openqa.grid.web.servlet.RegistrationServlet.doPost(RegistrationServlet.java:69)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:499)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:310)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.seleniumhq.jetty9.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Unknown Source)

BTW - 
Thank you for a wonderful tool.
You've helped me much on my project !

**Comment by aimmac23** [comment]
Thanks madaniel,

It looks like the fix for issue #27 didn't last as long I would have thought (the Selenium project changed a class visibility from public to package-protected). I'll revisit it tomorrow, and see what can be done.

Thanks for the feedback - its good to hear this project is bringing joy to the world :)

Alasdair

**Comment by aimmac23** [comment]
Hi madaniel,

Issue should be fixed for now in version 2.3, which I have just released.

Thanks,

Alasdair

**Comment by madaniel** [comment]
Thanks aimmac23 for your commitment and your good job :+1:
