### ISSUE TITLE
Issue with mac os

### ISSUE THREAD

**Issue by insatmc** [aimmac23/selenium-video-node#42]
Executing this code (1) return the error (2)

(1)

     java -cp proxy.jar:selenium-server-standalone-3.4.0.jar org.openqa.grid.selenium.GridLauncherV3 -servlets com.aimmac23.node.servlet.VideoRecordingControlServlet -proxy com.aimmac23.hub.proxy.VideoProxy -role node

(2)

    Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.aimmac23.node.servlet.VideoRecordingControlServlet.<clinit>(VideoRecordingControlServlet.java:40)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)

**Comment by insatmc** [comment]
Fixed using .jar instead of exporting the source code to a jar.

**Comment by aimmac23** [comment]
Hi insatmc,

I'm not sure how the packaging is different, but I'm glad you got it working in the end.

Thanks,

Alasdair
