### ISSUE TITLE
Could not create screenshot source on MacOS

### ISSUE THREAD

**Issue by ihorpadalko** [aimmac23/selenium-video-node#44]
I'm getting the traceback on my MacOS
06:08:51.634 INFO - Selenium build info: version: '3.4.0', revision: 'unknown'
06:08:51.638 INFO - Launching a Selenium Grid node
06:08:53.110 INFO - Will attempt to record at 30 frames per second - adjust this value  by setting -Dvideo.framerate=<value>
Exception in thread "main" java.lang.ExceptionInInitializerError
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.openqa.grid.web.utils.ExtraServletUtil.createServlet(ExtraServletUtil.java:38)
        at org.openqa.grid.internal.utils.SelfRegisteringRemote.addExtraServlets(SelfRegisteringRemote.java:291)
        at org.openqa.grid.internal.utils.SelfRegisteringRemote.<init>(SelfRegisteringRemote.java:101)
        at org.openqa.grid.selenium.GridLauncherV3$3.launch(GridLauncherV3.java:286)
        at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:99)
Caused by: java.lang.IllegalStateException: Could not create screenshot source for video encoder
        at com.aimmac23.node.VideoRecordController.<init>(VideoRecordController.java:75)
        at com.aimmac23.node.servlet.VideoRecordingControlServlet.<clinit>(VideoRecordingControlServlet.java:47)
        ... 7 more
Caused by: java.awt.AWTException: headless environment
        at java.awt.Robot.<init>(Robot.java:91)
        at com.aimmac23.node.RobotScreenshotSource.<init>(RobotScreenshotSource.java:21)
        at com.aimmac23.node.VideoRecordController.<init>(VideoRecordController.java:64)
        ... 8 more

The start script is:
java -cp selenium-video-node-2.3.jar:selenium-server-standalone-3.4.0.jar -Dvideo.framerate=30 org.openqa.grid.selenium.GridLauncherV3 -servlets com.aimmac23.node.servlet.VideoRecordingControlServlet -proxy com.aimmac23.hub.proxy.VideoProxy -role wd -nodeConfig ios-node-config.json

The node config:
$ cat ios-node-config.json
{
    "capabilities": [
        {
            "browserName": "safari",
            "version" : "10.1.1",
            "maxInstances": 1,
            "platform": "MAC"
        }
    ],
        "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
        "port": 5555,
        "hub":"http://10.8.68.100:8844",
        "maxSession": 1,
        "register": true,
        "registerCycle": 5000,
        "nodeStatusCheckTimeout": 5000,
        "nodePolling": 5000,
        "role": "node",
        "unregisterIfStillDownAfter": 60000,
        "downPollingLimit": 2
}

The color depth on MacOS is 32bit.

**Comment by ihorpadalko** [comment]
![screen shot 2017-07-20 at 15 42 05](https://user-images.githubusercontent.com/24293571/28424386-2b0bb5ba-6d76-11e7-8a2e-40a5311381f0.png)

**Comment by aimmac23** [comment]
Hi ihorpadalko,

That doesn't look good. It sounds like the Java screenshot functionality isn't working on your system?

A quick Google doesn't real anything - can you send me your Java version and OS X version?

You can also set "-Djava.awt.headless=false", and see what happens.

Thanks,

Alasdair

**Comment by ihorpadalko** [comment]
Hi Alasdair,

This option "-Djava.awt.headless=false" helped! 
The node is up and running now. 
Thanks!

My java ans OSX version, btw:
java version "1.8.0_141"
Sierra 10.12.5

**Comment by aimmac23** [comment]
Umm... I didn't expect that to really work.

I still think there's a problem somewhere, but I don't have access to a Mac to test it. I suspect there's some sort of incompatibility between the JVM and OSX - let's leave the issue open for a while in case someone else has seen the issue.
