### ISSUE TITLE
Cannot start the node using Selenium server standalone version 3.7.0

### ISSUE THREAD

**Issue by dinaosama91** [aimmac23/selenium-video-node#47]
When trynig to start the node using selenium 3.7.0.jar the following an exception is thrown:

13:51:03.592 INFO - Selenium build info: version: '3.7.0', revision: '2321c73'
13:51:03.592 INFO - Launching a Selenium Grid node
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/jna/NativeLib
rary
        at com.aimmac23.node.jna.JnaLibraryLoader.addNativePath(JnaLibraryLoader
.java:34)
        at com.aimmac23.node.jna.JnaLibraryLoader.extractJNABinariesIfAvailable(
JnaLibraryLoader.java:80)
        at com.aimmac23.node.jna.JnaLibraryLoader.init(JnaLibraryLoader.java:96)

        at com.aimmac23.node.RecordVideoCallable.<clinit>(RecordVideoCallable.ja
va:26)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at com.aimmac23.node.servlet.VideoRecordingControlServlet.<clinit>(Video
RecordingControlServlet.java:40)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.openqa.grid.web.utils.ExtraServletUtil.createServlet(ExtraServlet
Util.java:38)
        at org.openqa.grid.internal.utils.SelfRegisteringRemote.addExtraServlets
(SelfRegisteringRemote.java:298)
        at org.openqa.grid.internal.utils.SelfRegisteringRemote.<init>(SelfRegis
teringRemote.java:108)
        at org.openqa.grid.selenium.GridLauncherV3$3.launch(GridLauncherV3.java:
285)
        at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:99)
Caused by: java.lang.ClassNotFoundException: com.sun.jna.NativeLibrary
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 14 more

**Comment by aimmac23** [comment]
Hmm - it looks like JNA has been dropped from the main selenium project as of 3.7.0, which is why its no longer on the classpath.

For now if you download the dependency from:

 https://mvnrepository.com/artifact/net.java.dev.jna/jna/4.4.0 

And put it on the classpath, that should resolve the issue for now. We may have to bundle the dependency in the future...

Thanks,

Alasdair

**Comment by aimmac23** [comment]
Hi dinaosama91,

It looks like some other changes were made to Selenium 3.7.0 at the same time (constructor changes), so it looks like some code changes will be required. Hopefully I can take a look over the weekend.

Thanks,

Alasdair

**Comment by EugeneS30** [comment]
@aimmac23 That could be great as I am having the same issue here. Thanks a lot for support!

**Comment by aimmac23** [comment]
@EugeneS30 kindly submitted a pull request - I'll release it to Maven central.

I've taken a look at Selenium 3.7.1, and it looks like it has some breaking code changes - since we may have to drop compatibility, I'll try to handle that separately.

Thanks,

Alasdair

**Comment by aimmac23** [comment]
Released as version 2.5

**Comment by EugeneS30** [comment]
Hi Alasdair,

Happy to help and thank you for your work!
Could I possibly ask you few questions about this project? If yes, what is
the best way to contact you?


Thanks,
Eugene

**Comment by aimmac23** [comment]
Breaking changes released as version 2.6 - I couldn't figure out any way to support previous versions of Selenium when the DefaultRemoteProxy type signature changed.
