### ISSUE TITLE
[Selenium 3.7.0] - MutableCapabilities cannot be cast to org.openqa.selenium.remote.DesiredCapabilities

### ISSUE THREAD

**Issue by EugeneS30** [aimmac23/selenium-video-node#50]
One of the new features added in Selenium 3.7.0 is:

* Migrated from using `DesiredCapabilities` to either
  `MutableCapabilities` or (preferably) `ImmutableCapabilities`.

Currently that's causing the below error:

```
10:45:39.029 ERROR - Couldn't correct Selenium registration request - this code may need recompiling to support new code changes. Please file a bug against the selenium-video-node project, and attach this stacktrace.
java.lang.ClassCastException: org.openqa.selenium.MutableCapabilities cannot be cast to org.openqa.selenium.remote.DesiredCapabilities
        at com.aimmac23.hub.proxy.RegistrationRequestCorrector.correctCapabilities(RegistrationRequestCorrector.java:97)
        at com.aimmac23.hub.proxy.RegistrationRequestCorrector.access$300(RegistrationRequestCorrector.java:26)
        at com.aimmac23.hub.proxy.RegistrationRequestCorrector$V3ConfigurationCorrector.fixupConfig(RegistrationRequestCorrector.java:72)
        at com.aimmac23.hub.proxy.RegistrationRequestCorrector.correctRegistrationRequest(RegistrationRequestCorrector.java:33)
        at com.aimmac23.hub.proxy.VideoProxy.<init>(VideoProxy.java:35)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at org.openqa.grid.internal.BaseRemoteProxy.getNewInstance(BaseRemoteProxy.java:351)
        at org.openqa.grid.web.servlet.RegistrationServlet.process(RegistrationServlet.java:104)
        at org.openqa.grid.web.servlet.RegistrationServlet.doPost(RegistrationServlet.java:71)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:841)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.seleniumhq.jetty9.server.Server.handle(Server.java:564)
        at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:317)
        at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:251)
```

**Comment by aimmac23** [comment]
Thanks - now merged. I should check to see if we still need this code (I remember problems with some of the default options back in Selenium 2.x).

There's also been another change with Selenium 3.7.1 which isn't backwards-compatible - I'll push that fix out at the same time.

Thanks for the pull request,

Alasdair
