### ISSUE TITLE
Unable to launch selenium node by instructions

### ISSUE THREAD

**Issue by mosadchiy** [aimmac23/selenium-video-node#56]
After downloading
The latest "selenium-server-standalone" JAR from http://selenium-release.storage.googleapis.com/index.html
and
The latest "selenium-video-node" JAR from http://repo1.maven.org/maven2/com/aimmac23/selenium-video-node/

I'm not able to launch selenium node on my Windows 7 x64 machine. Console below:
D:\Selenium>java -cp selenium-video-node-2.7.jar;selenium-server-standalone-3.13.0.jar org.openqa.grid.selenium.GridLauncherV3 -servlets com.aimmac23.node.servlet.VideoRecordingControlServlet -proxy com.aimmac23.hub.proxy.VideoProxy -role wd

The output:
12:10:04.252 INFO [GridLauncherV3.launch] - Selenium build info: version: '3.13.0', revision: '2f0d292'
12:10:04.281 INFO [GridLauncherV3$3.launch] - Launching a Selenium Grid node on port 26279
12:10:04.802 INFO [JnaLibraryLoader.init] - 64-bit JVM detected - loading 64-bit libraries
12:10:04.904 INFO [VideoRecordController.<init>] - Will attempt to record at 15 frames per second - adjust this value  by setting -Dvideo.framerate=<value>
12:10:05.016 INFO [VideoRecordController.<init>] - Using Java AWT Robot Screenshot Source
Exception in thread "main" java.lang.ExceptionInInitializerError
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.openqa.grid.web.utils.ExtraServletUtil.createServlet(ExtraServletUtil.java:38)
        at org.openqa.grid.internal.utils.SelfRegisteringRemote.addExtraServlets(SelfRegisteringRemote.java:305)
        at org.openqa.grid.internal.utils.SelfRegisteringRemote.<init>(SelfRegisteringRemote.java:95)
        at org.openqa.grid.internal.utils.SelfRegisteringRemote.<init>(SelfRegisteringRemote.java:70)
        at org.openqa.grid.selenium.GridLauncherV3$3.launch(GridLauncherV3.java:311)
        at org.openqa.grid.selenium.GridLauncherV3.launch(GridLauncherV3.java:121)
        at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:81)
Caused by: java.lang.IllegalStateException: Display colour depth incorrect (should be 8 bits of red, blue and green). Currently: 5-6-5
        at com.aimmac23.node.RobotScreenshotSource.doStartupSanityChecks(RobotScreenshotSource.java:69)
        at com.aimmac23.node.VideoRecordController.<init>(VideoRecordController.java:47)
        at com.aimmac23.node.servlet.VideoRecordingControlServlet.<clinit>(VideoRecordingControlServlet.java:42)
        ... 9 more
Exception in thread "JNA Shutdown Hook Thread" java.lang.IllegalAccessError: tried to access method com.google.common.io.Files.fileTreeTraverser()Lcom/google/common/collect/TreeTraverser; from class com.aimmac23.node.jna.JnaLibraryLoader$1
        at com.aimmac23.node.jna.JnaLibraryLoader$1.run(JnaLibraryLoader.java:177)
        at java.lang.Thread.run(Unknown Source)

**Comment by aimmac23** [comment]
Hi mosadchiy,

It looks like the problem is on this line:

>  Caused by: java.lang.IllegalStateException: Display colour depth incorrect (should be 8 bits of red, blue and green). Currently: 5-6-5

Currently the native code that turns screenshots into YUV image data only supports a colour depth of 32-bits (24-bits, excluding alpha). If you increase the colour depth of your screen, it should work.

As a separate issue it looks like the "JNA Shutdown Hook" thread crashed, but that shouldn't affect the ability to start up/run.

Thanks,

Alasdair Macmillan

**Comment by aimmac23** [comment]
I've just released version 2.8, which won' have the error in the JNA shotdown hook thread.
