### ISSUE TITLE
java.security.InvalidParameterException: Error: com.aimmac23.hub.proxy.VideoProxy

### ISSUE THREAD

**Issue by phaseen** [aimmac23/selenium-video-node#61]
Could not register the node to hub it failed with invalid parameter exception.

13:20:06.065 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
13:20:06.315 INFO [GridLauncherV3.lambda$buildLaunchers$5] - Launching Selenium Grid hub on port 2800
2019-10-16 13:20:06.751:INFO::main: Logging initialized @984ms to org.seleniumhq.jetty9.util.log.StdErrLog
13:20:07.423 INFO [Hub.start] - Selenium Grid hub is up and running
13:20:07.423 INFO [Hub.start] - Nodes should register to http://127.0.0.1:2800/grid/register/
13:20:07.423 INFO [Hub.start] - Clients should connect to http://127.0.0.1:2800/wd/hub
2019-10-16 13:20:12.361:WARN:osjs.HttpChannel:qtp18823673-17: /grid/register
java.security.InvalidParameterException: Error: com.aimmac23.hub.proxy.VideoProxy
        at org.openqa.grid.internal.BaseRemoteProxy.getNewInstance(BaseRemoteProxy.java:369)
        at org.openqa.grid.web.servlet.RegistrationServlet.process(RegistrationServlet.java:103)
        at org.openqa.grid.web.servlet.RegistrationServlet.doPost(RegistrationServlet.java:70)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:865)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
        at org.seleniumhq.jetty9.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
        at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
        at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1242)

**Here is my command for node:**

java -Dwebdriver.chrome.driver="D:\Users\xxxx\Downloads\xxxx\chromedriver.exe" -cp selenium-video-node-2.9.jar;selenium-server-standalone-3.141.59.jar org.openqa.grid.selenium.GridLauncherV3 -servlets com.aimmac23.node.servlet.VideoRecordingControlServlet -proxy com.aimmac23.hub.proxy.VideoProxy -role wd -hub http://localhost:2800/grid/register -browser "browserName=chrome,version=ANY,maxInstances=5,platform=WINDOWS" -port 2803

**Node Logs:**

13:27:07.616 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
13:27:07.726 INFO [GridLauncherV3.lambda$buildLaunchers$7] - Launching a Selenium Grid node on port 2803
13:27:08.538 INFO [JnaLibraryLoader.init] - 32-bit JVM detected - loading 32-bit libraries
13:27:08.633 INFO [VideoRecordController.<init>] - Will attempt to record at 15 frames per second - adjust this value  by setting -Dvideo.framerate=<value>
13:27:08.694 INFO [VideoRecordController.<init>] - Using Java AWT Robot Screenshot Source
13:27:08.694 INFO [SelfRegisteringRemote.addExtraServlets] - binding com.aimmac23.node.servlet.VideoRecordingControlServlet to /extra/VideoRecordingControlServlet/*
2019-10-16 13:27:08.757:INFO::main: Logging initialized @1551ms to org.seleniumhq.jetty9.util.log.StdErrLog
13:27:09.038 INFO [WebDriverServlet.<init>] - Initialising WebDriverServlet
13:27:09.148 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 2803
13:27:09.167 INFO [GridLauncherV3.lambda$buildLaunchers$7] - Selenium Grid node is up and ready to register to the hub
13:27:09.382 INFO [SelfRegisteringRemote$1.run] - Starting auto registration thread. Will try to register every 5000 ms.
13:27:10.054 INFO [SelfRegisteringRemote.registerToHub] - Registering the node to the hub: http://localhost:2800/grid/register
13:27:10.273 INFO [SelfRegisteringRemote$1.run] - Couldn't register this node: Error sending the registration request: The hub responded with 500
13:27:15.335 INFO [SelfRegisteringRemote.registerToHub] - Registering the node to the hub: http://localhost:2800/grid/register
13:27:15.491 INFO [SelfRegisteringRemote$1.run] - Couldn't register this node: Error sending the registration request: The hub responded with 500

**Comment by phaseen** [comment]
This issue is resolved , it was class path issue i provided full path in the -cp and it worked.
